### ISSUE TITLE
Locking on windows is not advisory

### ISSUE THREAD

**Issue by brson** [danburkert/fs2-rs#15]
I wish I had more details offhand, but I'm just recalling some unexpected behavior I encountered recently.

I took an exclusive lock on a file on windows, and then subsequent I/O operations (I don't remember if they were reads or writes) started erroring.

Again, I'm sorry I don't have details offhand. It's late here.

**Comment by danburkert** [comment]
Indeed, file locks aren't advisory on Windows.  On Windows, `fs2` uses the [`LockFile`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365202(v=vs.85).aspx) API.  The fs2 docs say "File locks may only be relied upon to be advisory.", which is to say they may be enforced, but that can't be guaranteed on all platforms.

**Comment by brson** [comment]
Perhaps some clarification in the docs about platform specific behavior is warranted.

**Comment by brson** [comment]
Maybe you know the solution to the problem I have now. I have one handle open with a shared lock. Then I am trying to reopen that same handle to take another shared lock on it, but I can't open it because access denied.

**Comment by danburkert** [comment]
> Perhaps some clarification in the docs about platform specific behavior is warranted. I have found the differences in advisoriness difficult to work with because of unexpected file access errors on windows.

There is a note about the platform-specific behavior on the [`FileExt` trait](https://docs.rs/fs2/0.4.1/fs2/trait.FileExt.html#notes-on-file-locks).  I'm not too keen to re-document `flock` and `LockFile`, since there are many many differences.  Instead, I tried to document the common subset of behaviors that can be relied on.

> Maybe you know the solution to the problem I have now. I have one handle open with a shared lock. Then I am trying to reopen that same handle to take another shared lock on it, but I can't open it because access denied.

It's hard to say without knowing what platform you are on, and whether you are duplicating the file or re-opening it.  I recommend taking a look at the test cases in the library.  In `lib.rs` the test cases work on all platforms; in `unix.rs` and `windows.rs` the test cases are more or less documenting platform specific behavior.

**Comment by brson** [comment]
I suspect the problem I'm encountering is because open trying to open with write permission, and that the pattern I'm trying to use here is wrong-headed and needs a rewrite.

I guess there's nothing to be done about this issue.

**Comment by brson** [comment]
Thanks @danburkert

**Comment by danburkert** [comment]
No problem.
